### ISSUE TITLE
New hash torrent files provider ..

### ISSUE THREAD

**Issue by Draxler** [CIAvash/Magrent#2]
As you already know, 2 hash torrent files providers are offline for some time now and only one provider on Magrant is still active.. We don't know what future holds for these 2 providers so i have a question and proposal.
Is there any chance to add 4th provider into Magrant so we have at least 2 working providers instead of one ? 
http://thetorrent.org is provider with a lot of hash torrents files to offer and offers also a lot of hash torrent files Torrage provider (wich is offline at the momment) have. So i wonder if this provider could be included into next Magrant relese as 4th provider ?
Regards

**Comment by CIAvash** [comment]
Thanks for the suggestion.
At the first glance thetorrent.org looked good. I'll probably add it.

**Comment by CIAvash** [comment]
fixed in 7286d02c0b5a96ed53cbf86765aaa72fb8b6bf21

**Comment by Draxler** [comment]
Happy to help :smile: 

.. o great :+1:

**Comment by Draxler** [comment]
@CIAvash 
When would be this new update (1.0.2) available at Mozilla addodns ? 
( if it's not to much to ask :smile:  )

**Comment by CIAvash** [comment]
It was approved for AMO while I was writing this reply! :smile: So you can update now.

**Comment by Draxler** [comment]
:+1: 
------
