### ISSUE TITLE
Incompatible with Automatic Save Folder addon

### ISSUE THREAD

**Issue by vanowm** [CIAvash/Magrent#3]
Magrent seems to force downloading files to last save folder, without user prompt.

It also ignores setting from ASF addon https://addons.mozilla.org/firefox/addon/automatic-save-folder/

**Comment by CIAvash** [comment]
Magrent downloads files to the user's preferred downloads directory, which can be changed from Preferences' General tab.

So if it's downloading to the last save folder it would mean that Automatic Save Folder is changing the preferred downloads directory every time you download something, which is not Magrent's problem.

**Comment by vanowm** [comment]
Actually it is Magrent's problem, because my setting set to always ask where to save file, and it ignores it.

**Comment by CIAvash** [comment]
I was referring to "last save folder".

The file download prompt applies to the files that the browser itself is going to manage and download. But Magrent downloads the torrent files directly to the preferred downloads directory, so it's not a normal file download.

I wanted to do it with the download dialog(the browser way), but the current implementation was the best solution I could find with Mozilla's Add-on SDK.

**Comment by vanowm** [comment]
I understand Magrent works as designed, however it sure not user friendly regarding this, there is no easy way to change that setting without going through about:config or download another file somewhere else.

Perhaps, if download dialog is not available from SDK, maybe an inline option where user could specified where to save the files should be added instead? Just an idea.

P.S.
Issue is closed before it had a chance to get resolved ;)
